<?php

$todosDepartamentosQuery = "SELECT DEPARTAMENTO_ID, DEPARTAMENTOS_DESC FROM 229564reproenea.DEPARTAMENTO";
$todosAutorizadoresQuery = "SELECT AUTORIZADOR_ID, AUTORIZADOR_NOMBRE, AUTORIZADOR_APELLIDOS, AUTORIZADOR_EMAIL FROM 229564reproenea.AUTORIZADOR";
$maximaSolicidud = "SELECT MAX(SOLICITUD_ID)+1 AS SOLICITUD_MAX FROM 229564reproenea.SOLICITUD";
$solicitudPorValidadorQuery = "SELECT solicitud_id, departamento_id, nombre_solicitante, apellidos_solicitante, autorizador_id, descripcion_solicitante,	email_solicitante, status_id, fecha_alta, fecha_validacion,	fecha_cierre FROM 229564reproenea.solicitud WHERE status_id = 1 and autorizador_id = ";
$loginQuery = "SELECT usuario_id, nombre, apellido, role_id FROM 229564reproenea.usuario";
$updateSolicitudQuery = "UPDATE 229564reproenea.SOLICITUD SET";
$solicitudPorRealizarQuery = "SELECT solicitud_id, departamento_id, nombre_solicitante, apellidos_solicitante, autorizador_id, descripcion_solicitante,	email_solicitante, status_id, fecha_alta, fecha_validacion,	fecha_cierre FROM 229564reproenea.solicitud WHERE status_id = 2";
$existeTrabajoQuery = "SELECT TRABAJO_ID FROM 229564reproenea.TRABAJO WHERE SOLICITUD_ID = ";
$recuperaEncoladoQuery = "SELECT r1.tipo_id as TIPO_ID,r1.tipo_desc as TIPO_DESC,d1.detalle_id as DETALLE_ID,d1.descripcion as DESCRIPCION,d1.precio as PRECIO FROM 229564reproenea.tipo r1 inner join 229564reproenea.detalle d1 on r1.tipo_id = d1.tipo_id WHERE r1.tipo_id = 2 ORDER BY r1.tipo_id, d1.detalle_id";
$recuperaEspiralQuery = "SELECT r1.tipo_id as TIPO_ID,r1.tipo_desc as TIPO_DESC,d1.detalle_id as DETALLE_ID,d1.descripcion as DESCRIPCION,d1.precio as PRECIO FROM 229564reproenea.tipo r1 inner join 229564reproenea.detalle d1 on r1.tipo_id = d1.tipo_id WHERE r1.tipo_id = 1 ORDER BY r1.tipo_id, d1.detalle_id";
$recuperaVariosUnoQuery = "SELECT r1.tipo_id as TIPO_ID,r1.tipo_desc as TIPO_DESC,d1.detalle_id as DETALLE_ID,d1.descripcion as DESCRIPCION,d1.precio as PRECIO FROM 229564reproenea.tipo r1 inner join 229564reproenea.detalle d1 on r1.tipo_id = d1.tipo_id WHERE r1.tipo_id = 3 ORDER BY r1.tipo_id, d1.detalle_id";
$recuperaColorQuery = "SELECT r1.tipo_id as TIPO_ID,r1.tipo_desc as TIPO_DESC,d1.detalle_id as DETALLE_ID,d1.descripcion as DESCRIPCION,d1.precio as PRECIO FROM 229564reproenea.tipo r1 inner join 229564reproenea.detalle d1 on r1.tipo_id = d1.tipo_id WHERE r1.tipo_id = 4 ORDER BY r1.tipo_id, d1.detalle_id";
$recuperaByNQuery = "SELECT r1.tipo_id as TIPO_ID,r1.tipo_desc as TIPO_DESC,d1.detalle_id as DETALLE_ID,d1.descripcion as DESCRIPCION,d1.precio as PRECIO FROM 229564reproenea.tipo r1 inner join 229564reproenea.detalle d1 on r1.tipo_id = d1.tipo_id WHERE r1.tipo_id = 5 ORDER BY r1.tipo_id, d1.detalle_id";
$recuperaVariosDosQuery = "SELECT r1.tipo_id as TIPO_ID,r1.tipo_desc as TIPO_DESC,d1.detalle_id as DETALLE_ID,d1.descripcion as DESCRIPCION,d1.precio as PRECIO FROM 229564reproenea.tipo r1 inner join 229564reproenea.detalle d1 on r1.tipo_id = d1.tipo_id WHERE r1.tipo_id = 6 ORDER BY r1.tipo_id, d1.detalle_id";
$recuperaEncoladoDetalleQuery = "SELECT r1.tipo_id as TIPO_ID,r1.tipo_desc as TIPO_DESC,d1.detalle_id as DETALLE_ID,d1.descripcion as DESCRIPCION,d1.precio as PRECIO,td1.unidades as UNIDADES, td1.preciototal as PRECIOTOTAL FROM 229564reproenea.tipo r1 inner join 229564reproenea.detalle d1 on r1.tipo_id = d1.tipo_id left join 229564reproenea.trabajodetalle td1 on r1.tipo_id = td1.tipo_id and d1.detalle_id = td1.detalle_id WHERE r1.tipo_id = 2 and td1.solicitud_id = ";
$recuperaEspiralDetalleQuery = "SELECT r1.tipo_id as TIPO_ID,r1.tipo_desc as TIPO_DESC,d1.detalle_id as DETALLE_ID,d1.descripcion as DESCRIPCION,d1.precio as PRECIO,td1.unidades as UNIDADES, td1.preciototal as PRECIOTOTAL FROM 229564reproenea.tipo r1 inner join 229564reproenea.detalle d1 on r1.tipo_id = d1.tipo_id left join 229564reproenea.trabajodetalle td1 on r1.tipo_id = td1.tipo_id and d1.detalle_id = td1.detalle_id WHERE r1.tipo_id = 1 and td1.solicitud_id = ";
$recuperaVariosUnoDetalleQuery = "SELECT r1.tipo_id as TIPO_ID,r1.tipo_desc as TIPO_DESC,d1.detalle_id as DETALLE_ID,d1.descripcion as DESCRIPCION,d1.precio as PRECIO,td1.unidades as UNIDADES, td1.preciototal as PRECIOTOTAL FROM 229564reproenea.tipo r1 inner join 229564reproenea.detalle d1 on r1.tipo_id = d1.tipo_id left join 229564reproenea.trabajodetalle td1 on r1.tipo_id = td1.tipo_id and d1.detalle_id = td1.detalle_id WHERE r1.tipo_id = 3 and td1.solicitud_id = ";
$recuperaColorDetalleQuery = "SELECT r1.tipo_id as TIPO_ID,r1.tipo_desc as TIPO_DESC,d1.detalle_id as DETALLE_ID,d1.descripcion as DESCRIPCION,d1.precio as PRECIO,td1.unidades as UNIDADES, td1.preciototal as PRECIOTOTAL FROM 229564reproenea.tipo r1 inner join 229564reproenea.detalle d1 on r1.tipo_id = d1.tipo_id left join 229564reproenea.trabajodetalle td1 on r1.tipo_id = td1.tipo_id and d1.detalle_id = td1.detalle_id WHERE r1.tipo_id = 4 and td1.solicitud_id = ";
$recuperaByNDetalleQuery = "SELECT r1.tipo_id as TIPO_ID,r1.tipo_desc as TIPO_DESC,d1.detalle_id as DETALLE_ID,d1.descripcion as DESCRIPCION,d1.precio as PRECIO,td1.unidades as UNIDADES, td1.preciototal as PRECIOTOTAL FROM 229564reproenea.tipo r1 inner join 229564reproenea.detalle d1 on r1.tipo_id = d1.tipo_id left join 229564reproenea.trabajodetalle td1 on r1.tipo_id = td1.tipo_id and d1.detalle_id = td1.detalle_id WHERE r1.tipo_id = 5 and td1.solicitud_id = ";
$recuperaVariosDosDetalleQuery = "SELECT r1.tipo_id as TIPO_ID,r1.tipo_desc as TIPO_DESC,d1.detalle_id as DETALLE_ID,d1.descripcion as DESCRIPCION,d1.precio as PRECIO,td1.unidades as UNIDADES, td1.preciototal as PRECIOTOTAL FROM 229564reproenea.tipo r1 inner join 229564reproenea.detalle d1 on r1.tipo_id = d1.tipo_id left join 229564reproenea.trabajodetalle td1 on r1.tipo_id = td1.tipo_id and d1.detalle_id = td1.detalle_id WHERE r1.tipo_id = 6 and td1.solicitud_id = ";


?>
